[package]
name = "auth"
version = "0.1.0"
authors = ["Alexander Lyon <arlyon@me.com>"]
edition = "2018"

[dependencies]
async-std = { version = "1.8.0", features = ["unstable", "async-channel", "attributes"] }
async-trait = "0.1.42"
sqlx = { version = "0.5", features = ["runtime-async-std-rustls", "mysql", "offline"] }

bincode = "2.0.0-dev"
serde = { version = "1.0.118", features = ["derive"] }
serde_yaml = "0.8.14"

derive_more = "0.99.11"
derivative = "2.1.1"

anyhow = "1.0.36"
thiserror = "1.0.22"
human-panic = "1.0.3"

num_enum = "0.5.1"
rustyline = "7.1.0"
static_assertions = "1.1.0"
assert-size-attribute = { path = "../../crates/assert-size-attribute" }
structopt = "0.3.21"
rand = "0.8.0"
lazy_static = "1.4.0"
num-bigint = "0.2"

tracing = "0.1.22"
tracing-subscriber = { version = "0.2.15", features = ["tracing-log"] }
tracing-futures = "0.2.4"

colored = "2.0.0"
termion = "1.5.5"
tui = "0.13.0"
tui-logger = { version = "0.4.8" }

wow-srp = { path = "../../crates/wow-srp" }
game = { path = "../../crates/game" }
mysql = { path = "../../crates/mysql" }
enumflags2 = "0.7.0-preview1"

[dev-dependencies]
test-case = "1.0.0"
