[package]
name = "mysql"
version = "0.1.0"
authors = ["Alexander Lyon <arlyon@me.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.42"
game = { path = "../game" }
lazy_static = "1.4.0"
rand = "0.8.0"
sha-1 = "0.9.2"
sqlx = { version = "0.4.2", features = ["runtime-async-std-rustls", "mysql"] }
srp = "0.5.0"
