version: "3.9"
x-log-level: &log-level
  RUST_LOG: "azerust_world,azerust_auth"
services:
  world:
    image: ghcr.io/arlyon/azerust-world:master
    profiles: ["server"]
    build:
      context: .
      target: world
    depends_on: [database]
    environment: *log-level
    volumes:
      - ./config-world-compose.yaml:/config.yaml:Z
    ports:
      - "8085:8085"
      - "9001:9001"
  auth:
    image: ghcr.io/arlyon/azerust-auth:master
    profiles: ["server"]
    build:
      context: .
      target: auth
    depends_on: [database]
    environment: *log-level
    volumes:
      - ./config-auth-compose.yaml:/config.yaml:Z
    ports:
      - "3724:3724"
      - "8000:8000"
      - "9000:9000"
  database:
    image: "mariadb:10"
    environment:
      MYSQL_ROOT_PASSWORD: azerust
    ports:
      - "3306:3306"
    volumes:
      - ./schema:/docker-entrypoint-initdb.d:Z
      - ./data:/var/lib/mysql:Z
