version: "3.9"
services:
  auth:
    image: ghcr.io/arlyon/azerust-auth:master
    build:
      context: .
    depends_on: [database]
    environment:
      AZERUST_LOGIN_DATABASE: mysql://root:azerust@database/auth
      RUST_LOG: mysql=DEBUG,auth=DEBUG,game=DEBUG
    volumes:
      - ./config-compose.yaml:/config.yaml:Z
    ports:
      - "3724:3724"
      - "8000:8000"
  database:
    image: "mariadb:10"
    environment:
      MYSQL_ROOT_PASSWORD: azerust
    ports:
      - "3306:3306"
    volumes:
      - ./schema:/docker-entrypoint-initdb.d:Z
      - ./data:/var/lib/mysql:Z
