[package]
name = "assert-size-attribute"
version = "0.1.0"
authors = ["Alexander Lyon <arlyon@me.com>"]
edition = "2018"
license = "MIT"

[lib]
proc-macro = true

[dependencies]
quote = "1.0.7"
syn = "1.0.54"
