[package]
name = "wow-srp"
version = "0.1.0"
authors = ["Alexander Lyon <arlyon@me.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
lazy_static = "1.4"
num-bigint = "0.4"
rand = "0.8"
serde = { version = "1", features = ["derive"] }
sha-1 = "0.9"
sqlx = "0.5"
tracing = "0.1"
